### ISSUE TITLE
Fix the map

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#68]

**Comment by KoleckoOrg** [comment]
I was not able to show any puzzle there, but maybe I just did something wrong.
If need improvement with respect to main and final puzzles anyway.

**Comment by KoleckoOrg** [comment]
BTW should the puzzles be visible in the map ATM?
I have a script for seeding the puzzles, sifry.rb in iKolečko folder in the Google Drive (it contains some critical private data for the puzzles like solutions, therefore I opted not to put it into the git) which I used to seed puzzles for yesterdays mass test and I was not able to show any puzzle in the map. Any idea what went wrong?

**Comment by mfrodl** [comment]
There was a bug in rendering the view which I already fixed (will push soon).

In addition, I am going to simplify the map icons. Currently, we distinguish between unvisited, visited and solved puzzles. Combining this with puzzle types (main, secondary and final) would introduce too many different icons in the map, possibly making it more confusing to read and also costing me extra time to get everything right.

That's why I think it makes sense to only show puzzle type and not care whether it has been visited or solved.

**Comment by mfrodl** [comment]
Did a quick fix but further testing needed.
