### ISSUE TITLE
Puzzle opening should send notifications to team

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#72]
Don't really know how to tackle this as rest of the stuff is client-side driven, while this would need some running timer on the server side?

If this is too complicated, we might do this manually during the game.

**Comment by mfrodl** [comment]
I can try to implement this.

I wouldn't worry much about the client side polling / server push stuff. I think we can safely work with the assumption of [compulsive reloading](https://xkcd.com/1466/).

**Comment by mfrodl** [comment]
By the way, does this apply to all puzzles or just the mains?

**Comment by mfrodl** [comment]
Or just the non-mains? :-)

**Comment by mfrodl** [comment]
Okay, assuming we only want to notify teams about secondary puzzles (because the main/final ones have to be paid for, right?), this should be implemented by 17693a06c2d5bcf195b10abb7e02ab2c58c70d82.

Note that to make this thing work properly, the rules in `config/schedule.rb` have to be converted into a crontab first.

1. (_in development only_) In `config.schedule.rb`, change `environment: 'production'` to `environment: 'development'`.
2. Run `whenever --update-crontab`.

Now the job will poll the database every minute, check for newly opened puzzles and send a notification to all teams.

**Comment by KoleckoOrg** [comment]
Yeah, when you buy a main, it should directly redirect you to the list of puzzles, same thing when you solve the last main and the final gets revealed, there is no need for a notifications.

**Comment by mfrodl** [comment]
Closing per https://github.com/mfrodl/kolecko/issues/72#issuecomment-532597278.
